#Login page Keywords
user_id_x="xpath://input[@automationid='enterLoginUsername']"
user_pass_x="xpath://input[@automationid='enterLoginPassword']"
loginButton_x="xpath://button[@automationid='loginButton']"
forcelogin_heading_x="xpath://*[@automationid='confirmationModalTitle' and text()='Force Login']"
forcelogin ="xpath://button[@automationid='confirmationBtn1']"
work_mode_list="xpath://input[@name='workingMode']/following-sibling::label"
workmode_nextbutton="xpath://button[span[text()='Next']]"
voice_campaign_input="xpath://input[@placeholder='Select Voice Campaign']"
voice_campaign_list="xpath://ul[@class='select2-results__options']/li"
campaignselection_nextbutton_x="xpath://span[text()='Next']/parent::button"
extension_selection_input="xpath://span[@automationid='dispositionCodesShowListItems']"
extension_selection_list="xpath://ul[@role='tree']/li"
numberenter_after_extension_selection="xpath://input[@placeholder='Enter Number']"
extensionselection_nextbutton="xpath://button[@automationid='extensionSaveBtn']"
welcome_user = "xpath://span[@automationid='welcomeUser']"
agent_preferences_shown = "XPATH://div[@automationid='agentPreferenceContainer']"
agent_preferences_options = "XPATH://div[@automationid='agentPreferenceContainer']/ul/li"
agent_logout = "XPATH:'//li[@automationid='logoutBtn']"
